### ISSUE TITLE
Investigate big video upload limitation

### ISSUE THREAD

**Issue by andersruberg** [leocrawford/picasawebsync#15]
When trying to upload big video files I get this error.
'Request Entity Too Large', 'Video file size exceeds 104857600'
I guess that is due to googlecl limation or? Too bad, I was hoping to use google+ for easy backup of video files. Now I have to do it through the web interface.

**Comment by boygiandi** [comment]
I see the current limit of file size in your code is 1Gb. I know a guy said he can bypass that limitation, but the price of his script is a bit high. I'm trying to looking on the internet but no luck. Do you have any idea ?

**Comment by leocrawford** [comment]
I'm afraid not. This isn't something I've looked at.

I'm going to close this issue now, but happy to reopen if anyone has a patch to offer
