### ISSUE TITLE
Path handling on Windows

### ISSUE THREAD

**Issue by BVA64** [leocrawford/picasawebsync#23]
When uploading a new album on Windows a \ was added to the beginning of the album name in Google Plus. This resulted also in the album being downloaded with the new name on a subsequent sync.

I traced this to the regexp that removes the first / from the file name but this works only on Linux systems. I have replaced in my poll request the regexp with a string replace using the predefined platform specific path separator so it should work on both systems now. 8a10f39787ae5bfcca4e47897f261d3cc9c4db7b

P.S.: My editor has stripped all trailing white spaces from the code... Sorry...

**Comment by leocrawford** [comment]
I'm pretty sure this got merged in a while back. Let me know if I'm wrong.
