### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by rhillis2004** [leocrawford/picasawebsync#24]
I don't seem to be able to log in anymore. Is this script no longer working because of the switch to OAuth2?

**Comment by leocrawford** [comment]
Thanks for the report. I'm having the same problem, and will try and solve asap.

**Comment by leocrawford** [comment]
Hopefully fixed. Let me know

**Comment by rhillis2004** [comment]
Just one thing. Exactly which API are you using because there doesn't seem to be one for Picasa anymore.

**Comment by leocrawford** [comment]
I'm using this API which seems valid, apart from the fact it doesn't seem to support oauth2 which is now the only option. Is that the same conclusion you came to?

https://developers.google.com/picasa-web/

I've used this cludge to get it (seemingly) working.

http://stackoverflow.com/questions/20248555/list-of-spreadsheets-gdata-oauth2/29157967#29157967

This post (and others) bemoan the absence of an API on google photos.

https://rocketeer.be/blog/2015/05/google-photos/

**Comment by rhillis2004** [comment]
I agree. I'll see if I can get it to work.

On Tue, Jun 2, 2015 at 4:22 AM, Leo Crawford <notifications@github.com>
wrote:

> I'm using this API which seems valid, apart from the fact it doesn't seem
> to support oauth2 which is now the only option. Is that the same conclusion
> you came to?
>
> https://developers.google.com/picasa-web/
>
> I've used this cludge to get it (seemingly) working.
>
>
> http://stackoverflow.com/questions/20248555/list-of-spreadsheets-gdata-oauth2/29157967#29157967
>
> This post (and others) bemoan the absence of an API on google photos.
>
> https://rocketeer.be/blog/2015/05/google-photos/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leocrawford/picasawebsync/issues/24#issuecomment-107856850>
> .
>



-- 
Richard Hillis
23 Walnut Knoll
Canton, MA 02021
