### ISSUE TITLE
Error on uploading

### ISSUE THREAD

**Issue by tessie** [leocrawford/picasawebsync#26]
Failed to UPLOAD_LOCAL on Home image.jpg identified as LOCAL_ONLY. This was due to (404, 'Not Found', 'Unknown user.')

**Comment by leocrawford** [comment]
Could you try going back one version and see if that works. I have an idea what may have gone wrong.

**Comment by tessie** [comment]
@leocrawford  can you be more specific.

**Comment by leocrawford** [comment]
There are two possible causes for this, which I'm keen to isolate.

If you download the latest copy from the "bug" branch:

https://github.com/leocrawford/picasawebsync/tree/bug

and try that, it will allow me to tell which of the two possible problems it is you're having.

**Comment by tessie** [comment]
WARNING: Failed to UPLOAD_LOCAL on Home image.jpg identified as LOCAL_ONLY. This was due to (404, 'Not Found', 'Unknown user.')

@leocrawford  where are we passing username.I have infact commented the args.username line number 667

**Comment by leocrawford** [comment]
That problem should have been fixed in the bug branch I posted. I'm keen to see if that works for you before examining the other commit which may have problems.

**Comment by tessie** [comment]
https://github.com/leocrawford/picasawebsync/blob/bug/picasawebsync.py#L667
and my command line  python picasawebsync.py -d images

**Comment by leocrawford** [comment]
I'm slightly confused. We know that version doesn't work, and I've pointed you at a branch which might. It would be useful to test against the branch

**Comment by tessie** [comment]
ok.can you tell me step by step from cloning the right branch

**Comment by leocrawford** [comment]
The easiest thing to do is overwrite your downloaded picasawebsync.py with this one https://github.com/leocrawford/picasawebsync/blob/bugfix/picasawebsync.py

**Comment by tessie** [comment]
That works.as from the op of the script.I could not find in gooogle photos

**Comment by leocrawford** [comment]
Sorry. I'm confused by your response. Is that everything working OK now?

**Comment by tessie** [comment]
opps no WARNING: Failed to UPLOAD_LOCAL on Home image.jpg identified as LOCAL_ONLY. This was due to (404, 'Not Found', 'Unknown user.')

**Comment by leocrawford** [comment]
OK. I've managed to replicate (I had previously tested read only mode). It's a small bug, now fixed and I'm part way through updating my own collection using the latest version.

**Comment by tessie** [comment]
@leocrawford  can you explain the fix

**Comment by leocrawford** [comment]
In my attempt to work around the oauth2 problems I had mistakenly removed
the parameter to tell picasaweb to use the users default email address.
Look at the diff to see what I changed.
