### ISSUE TITLE
Cannot upload mp4 videos

### ISSUE THREAD

**Issue by gowthamgts** [leocrawford/picasawebsync#33]
I've a directory with a sample image and video. While running the program, the image is successfully uploaded while it shows an error for the video as follows:

    Skipped vids\bunny.mp4 (because can't upload file of type video/mp4).

So, are videos not supported?

**Comment by leocrawford** [comment]
By default --format is set to photo only, you probably want video or both.

**Comment by gowthamgts** [comment]
Thank you so much. I missed it.

**Comment by gowthamgts** [comment]
Hey, that's actually working for smaller files. But, when I tried to upload a bigger file less than 1GB, it shows the following error:

    WARNING: Failed to UPLOAD_LOCAL on Home Chandi.mp4 identified as LOCAL_ONLY. This was due to [Errno 32] Broken pipe

Also, I cannot upload `mkv` files. They are supported by Picasa, but I cannot upload them.

**Comment by leocrawford** [comment]
The file type is easy to fix. Towards the bottom of the code is an enumeration with video mime types. Feel free to add, test and submit a patch. 

Re the file size I have no idea? Is it airways exactly 1gb it fails at?

**Comment by gowthamgts** [comment]
Yeah I go through the code and issued a pull request supporting the .mkv. And the file size is 745MB.

**Comment by leocrawford** [comment]
Thanks for the pull. Merged.

**Comment by leocrawford** [comment]
I'm afraid I'm unlikely to look into the file size issue. I suspect google is closing the connection for some reason, but I don't have time to look into it. Happy to take a patch.

**Comment by gowthamgts** [comment]
@leocrawford Issue happens only for larger videos. Smaller ones work fine.
