### ISSUE TITLE
photos.google.com

### ISSUE THREAD

**Issue by JobExpert** [leocrawford/picasawebsync#36]
does Picasa web sync support 16 megapixels (MP)  and videos up to 1080p as in google photos instead of 2048?

https://support.google.com/photos/answer/6220791

High quality
Unlimited free storage.
Regular cameras: Recommended for phones or point-and-shoot cameras that are 16 megapixels (MP) or less.
Uses: Good for typical printing and sharing.
Size: Saves high-quality photos and videos while reducing size.

**Comment by ehrepli** [comment]
The API from google has limitations, 100Mb for videos, not sure it depends on resolution but you will not be able to upload much at 1080p. Using the web or the picasa app, i think limit is 10Gb.

As for the pictures, there is a limitation on the API as well, but I'm not sure if it depends on size or resolution at this time, I'm testing, though.

**Comment by JobExpert** [comment]
Is there an upload API for Google Photos (photos.google.com)?
http://stackoverflow.com/a/33456071

for what i'm understand it that the photos.google desktop uploader should call some API to upload the photos and the videos.

https://photos.google.com/apps
Is it diffrent API then picasa API?

maybe we can copy the api call of https://photos.google.com/apps?

i think that the https://support.google.com/photos/answer/6220791 refer to https://photos.google.com/apps API using photos.google.com API.

**Comment by ehrepli** [comment]
Not sure, I have not been able to find any reference to a photos api. All I have found is some information saying that the photos use the picasa api.

**Comment by leocrawford** [comment]
Thanks for the suggestion and thanks both for the research. I suspect at some stage the picasa API will be deprecated and the photos one introduced. The API we're using already requires a cludge to work with oauth2, which is mandated. 

I'm afraid I'm not in a position to do any non-trivial code changes, so I'll have to rely on patches if anyone wants to submit one - if not I guess we wait for google.

**Comment by Webreaper** [comment]
Not sure why Google would take that approach, given that Google Photos is
just a facade over the Picasa back end storage. The API works fine, and for
them to change it or deprecate it would break thousands of client apps....

**Comment by leocrawford** [comment]
Worth reading this:

https://developers.google.com/gdata/docs/directory

You'll see most of the data APIs are deprecated, or are planned to be.

**Comment by Webreaper** [comment]
Cool, handy to know (I've written a java/Mac Picasa sync app, also called
Picasync... ) so will need to upgrade it...). Thanks.

**Comment by leocrawford** [comment]
Do you have an idea what you might replace it with? The issue seems to be is that there is no current API for google photos. The pcasa/data API sort of works if you hack the authentication, but there are missing features.

**Comment by leocrawford** [comment]
I'm closing this issue unless anyone can suggest a tangible way forward. It feels like a waiting game
