### ISSUE TITLE
wrong date using shrink option

### ISSUE THREAD

**Issue by ManuCart** [leocrawford/picasawebsync#42]
with args
````
--shrink -m syncUpload --allowDelete remote --override:SAME UPDATE_REMOTE_METADATA --noupdatealbummetadata --purge
````
the date of the photo is wrong on google photos

**Comment by leocrawford** [comment]
Could you provide more info? Is this image being uploaded or already there?
What date should it get and what does it get? Does the actual date match
uploaded time, or modified time or some such?

**Comment by ManuCart** [comment]
It' from new image uploaded.
Photo date is the uploaded date and not the EXIF date.

**Comment by ManuCart** [comment]
I found my error, I forgeten to install jhead
