### ISSUE TITLE
Duplicate albums get created when there are too many existing albums

### ISSUE THREAD

**Issue by derrenbrown** [leocrawford/picasawebsync#46]
Hi author / developers,

First off, thank you so very much for writing this amazing sync application. I started using it last week. And I use it multiple times a day.

I have more than 5000 existing albums on Google photos already. When I use `picasawebsync`, it seems to me that it may not be able to "see" all of the existing web albums. During sync (i.e. upload), it creates duplicate albums with the same names that already exist on Google Photos. 

I took a brief look at the source code and couldn't figure out what exact went wrong. But i suspect that it might be due to limitation of the Picasa API. Paginations / iterations may be needed in order to retrieve all the existing web albums out there, especially when there are thousands of them.

I would greatly appreciate it if someone could fix up this one, or point me to the correct way of using `picasawebsync`. It's creating even more web albums to my Google photos. Every day.

Thanks in advance!

P.S: It would be superb if a new functionality could be added to "consolidate" all albums with the same name into one.

**Comment by leocrawford** [comment]
Thanks for your feedback, a most intriguing problem.

The check that matches web album names and file names is the line in scanWebAlbums

    if webAlbumTitle in self.albums: 

As the names are duplicates (are they exact) then it seems likely that either we are not fetching every web album (as you suggest) of for some reason it is excluded (there is an exclude option, are you using it).

In the first place I suggest you enable verbose mode, and post the complete log providing an example of one or more albums that have been duplicated.

Even better would be to do the same with a simpler test case, but I see that may be hard.

**Comment by leocrawford** [comment]
I've closed this as no response. Feel free to reply to my question if you're still interested in a fix
