### ISSUE TITLE
Question about albums name

### ISSUE THREAD

**Issue by ManuCart** [leocrawford/picasawebsync#47]
Happy new year!

My question is about albums name

I order my photos like that ````/photos/2017/2017-01-01 Happy New Year/Photo1.jpg````
And I want only ````Happy New Year```` in album name
How to do that ?
I try with ````-n "['{0}', '{1}']"```` but not working.

**Comment by leocrawford** [comment]
Happy New Year!

I think you're looking for the namingextract option, check out the docs (and feel free to suggest an improvement if not clear)

Let me know if this isn't what you're looking for.
