### ISSUE TITLE
Insert is no longer supported

### ISSUE THREAD

**Issue by jrodan** [leocrawford/picasawebsync#50]
Hi, 

I have the following problem:

$ python picasawebsync.py -d ~/Pictures/2017\ sample01/ -m syncUpload
Excluding $. on client and $. on server
Not Attempting to write date to album Profilfotos
WARNING: Failed to UPLOAD_LOCAL on Home 20160825_120412.jpg identified as LOCAL_ONLY. This was due to (501, 'Not Implemented', 'Insert is no longer supported')
WARNING: Failed to UPLOAD_LOCAL on Home 20160825_114337.jpg identified as LOCAL_ONLY. This was due to (501, 'Not Implemented', 'Insert is no longer supported')
WARNING: Failed to UPLOAD_LOCAL on Home 20160825_114019.jpg identified as LOCAL_ONLY. This was due to (501, 'Not Implemented', 'Insert is no longer supported')
Not Attempting to write date to album Home
Finished transferring files. Total files found 3, composed of {'DELETE_REMOTE': 0, 'SILENT': 0, 'UPLOAD_LOCAL': 3, 'UPDATE_REMOTE_METADATA': 0, 'DELETE_LOCAL': 0, 'TAG_REMOTE': 0, 'DOWNLOAD_REMOTE': 0, 'REPORT': 0, 'REPLACE_REMOTE_WITH_LOCAL': 0}

Is there any solution for that?

Thanks and regards

**Comment by leocrawford** [comment]
Hi. Has this ever worked, or did it stop working?

What version of gdata do you have installed?

**Comment by leocrawford** [comment]
http://regex.info/blog/lightroom-goodies/issues

This seems to indicate that it's album creation that is th eproblem, and it's my guess that this is the end of the road for the API. :-(

**Comment by leocrawford** [comment]
Based on this, I think the project is dead. :-(

https://developers.google.com/picasa-web/docs/3.0/releasenotes
